version: "3"
services:
  database:
    image: "postgres:14"
    container_name: database
    volumes:
      - ./database:/var/lib/postgresql/data
    networks:
      - network1
    env_file:
      - .env
    ports:
      - "${DB_PORT}:5432"

  backend:
    build: ./backend
    container_name: backend
    networks:
      - network1
    ports:
      - "3001:3001"
    depends_on:
      - database
      - libretranslate
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - /home/ag1320/polyglot/utils:/app/utils

  frontend:
    build: ./frontend
    container_name: frontend
    networks:
      - network1
    ports:
      - "5173:5173"
    depends_on:
      - backend
    env_file:
      - .env
    volumes:
      - ./frontend:/app
      - /home/ag1320/polyglot/utils:/app/utils

  libretranslate:
    image: libretranslate/libretranslate:latest
    container_name: libretranslate
    networks:
      - network1
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./lt-models:/home/libretranslate/.local
    restart: unless-stopped
  opentts:
    image: synesthesiam/opentts
    ports:
      - "5500:5500"
    env_file:
      - .env
    networks:
      - network1

networks:
  network1:
    driver: bridge
