version: "3"
services:
  database:
    image: "postgres:14"
    volumes:
      - ./database:/var/lib/postgresql/data
    networks:
      - network1
    container_name: database
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"

  backend:
    networks:
      - network1
    build: ./backend
    ports:
      - "3001:3001"
    container_name: backend
    depends_on:
      - database
    environment:
      DB_CONNECTION_STRING: ${DB_CONNECTION_STRING}
    volumes:
      - ./backend:/app
    env_file:
      - .env.${NODE_ENV}

  frontend:
    networks:
      - network1
    build: ./frontend
    ports:
      - "5173:5173"
    container_name: frontend
    depends_on:
      - backend
    volumes:
      - ./frontend:/app

networks:
  network1:
    driver: bridge
